[versions]
api = "82"
material = "1.12.0"
multidex = "2.0.1"

[libraries]
api = { module = "de.robv.android.xposed:api", version.ref = "api" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version = "22.0.2" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
