-keep class com.app.catsmoker.GameUnlocker
-keep class com.app.catsmoker.MyWebViewActivity
-keep class com.app.catsmoker.MainActivity
-keep class com.app.catsmoker.CrosshairOverlayService
-keep class com.app.catsmoker.EditQuality